travis:
  secure:
    BINSTAR_TOKEN: aeiE1YIerydgcdmNRCDGxqqYSJ4BtVFnxyrT644bEGtNHQlrILLb/qQUtq8nSpO9hB+BYzgqm1R55OY50EQawpMDqDuYHG38sg9IsZ31R+kCAgv+TglR/CDMqrD2ruMCKz0BsFH8Xk2H04icMPLD7DndPG9qZprtNb+aiAnnCu52TJ5BOT/mbKeWOYGhTpiYRSIdN9xKruyfqygSeYKbaChcHva8/cqABLHIVpnz+InDi11Q5UiPz4Lujl8rYguH/eCvys3u+HMqMvRkVwMERfG9hxbdpZ2IaPRSa6T4tB2StzxacE+Gfbo2GIYzImZGWNlvbMsB978NyPThK/oAw+QTFQASS9t9DL7Li8Q2ddtppFuP+tu6ZZOhfkRKFxPYJSOL/X0qaAOqwNa+6Hq0minuUx6ZaFFPkCrKU/x7/E6laZHIHSjckIr6sE/y8SDH6pMBpvEIv8fNHabefopvA3TtfjGGHtD0RPaMqGHe1TWePy7xp/P6hikKQ7O+MjO2sZHOMECYv511UFyrK/g49wENMsNu0tkMU5N/4llso0Q9SDc/dpz9TU+8VVkt/nsTDcXc404dNHu9sEYwoyeKAfg6RoicMBSwzF99pCH41nllqclgs9xZTmu4cCIBh13VRUon7NIz1kTXufvwSBPo4OYXMzrdDYhjaSidBWMvW/g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
